# Project: ROGUEGEN
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = src/main.o src/dungeon.o src/utility.o
LINKOBJ  = src/main.o src/dungeon.o src/utility.o
LIBS     = -L"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib" -L"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"E:/CPPProjects/ROGUEGEN/lib" -lncurses -g3
INCS     = -I"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/CPPProjects/ROGUEGEN/include"
CXXINCS  = -I"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"E:/CPPProjects/ROGUEGEN/include"
BIN      = ROGUEGEN.exe
CXXFLAGS = $(CXXINCS) -std=gnu99 -g3
CFLAGS   = $(INCS) -std=gnu99 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

src/main.o: src/main.c
	$(CC) -c src/main.c -o src/main.o $(CFLAGS)

src/dungeon.o: src/dungeon.c
	$(CC) -c src/dungeon.c -o src/dungeon.o $(CFLAGS)

src/utility.o: src/utility.c
	$(CC) -c src/utility.c -o src/utility.o $(CFLAGS)
